Feature: Pair Categories
Penumbra-Sync/client pull request #35
Opened 2023-01-15 11:51 UTC by Nia292

Implemented pair categories:
- Paired users can now get tags
- Tags get rendered into the main UI as groups
- Tags are persistently stored on the local configuration

2023-01-15 15:11 UTC, rootdarkarchon requested changes
Looks good overall, can you provide screenshots of functionality as intended, workflow etc.

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/Configuration.cs
> +    public Dictionary<string, List<string>> UidPairedUserTags = new(StringComparer.Ordinal);
this should be per server

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/UI/CompactUI.cs
> +        _tagHandler = new TagHandler(_configuration);
simplify by using `= new(_configuration)`

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/UI/CompactUI.cs
> +        }
add `UIShared.AttachToolTip` with an appropriate tooltip

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/UI/Components/SelectGroupForPairUi.cs
> +        private bool _opened;
why does `_open` and `_opened` exist, the naming is confusing

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/Configuration.cs
> +    public Dictionary<string, List<string>> UidPairedUserTags = new(StringComparer.Ordinal);
could also be optional, idk.

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/UI/Components/SelectGroupForPairUi.cs
> +            ImGui.Checkbox(name, ref hasTag);
should this not be `if(ImGui.Checkbox(name, ref hasTag)) { … }`

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/UI/UIShared.cs
> +    public static void FontTextUnformatted(string text, ImFontPtr font)
theoretically `Unformatted` can be omitted as I rarely to never use Formatted to begin with.

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/UI/Handlers/TagHandler.cs
> +            result.Sort(StringComparer.OrdinalIgnoreCase);
why are you using an inplace sort here instead of doing `AvailablePairTags.OrderBy(t => t).ToList()`

2023-01-15 15:11 UTC, rootdarkarchon commented on MareSynchronos/UI/Handlers/TagHandler.cs
> +            if (tagsForPair.Count <= 0)
This will never be smaller than 0 and can be rewritten as `!tagsForPair.Any()`

2023-01-18 16:40 UTC, Nia292 commented on MareSynchronos/UI/Components/SelectGroupForPairUi.cs
> +        private bool _opened;
Renamed them to _show and _opened now. One controls if the popup is supposed to be opened, and one is set to true after the `ImGui.OpenPopup` has been called. It's a bit tricky, I thought I could entirely avoid it, but because I am adding the name to the title of the modal, I would need to derive the name in `public void Open(ClientPairDto pair)`. And that feels a bit messy.

So it's been moved to two states, like in the `GroupPanel` for the syncshells

2023-01-18 16:40 UTC, Nia292 commented on MareSynchronos/UI/Handlers/TagHandler.cs
> +            result.Sort(StringComparer.OrdinalIgnoreCase);
Because I didn't know better D:

2023-01-18 16:48 UTC, Nia292 commented
> > Something like these? https://i.imgur.com/wnKF1VT.png
> > 
> > * overview of UI
> > * potential for various groups
> > * pairs can be in multiple groups (Kuplo Kop is a friend and also a moogle)
> > 
> > https://i.imgur.com/tZncDG2.png
> > 
> > * The "select groups" modal
> > * create groups here
> > 
> > https://i.imgur.com/wdWDkcL.png
> > 
> > * Pause pairing and resume pairing for groups
> 
> This doesn't look too bad. How do you collapse/expand folders? Are they permanently open? If yes they need a way to be collapsible.

They currently just open/close on click. I could attach a tooltip or I could use the same button that exists for syncshells. Though that would clutter it a bit more

2023-01-18 17:01 UTC, rootdarkarchon commented
> > This doesn't look too bad. How do you collapse/expand folders? Are they permanently open? If yes they need a way to be collapsible.
> 
> They currently just open/close on click. I could attach a tooltip or I could use the same button that exists for syncshells. Though that would clutter it a bit more.
> 
> Burger menu here: https://i.imgur.com/fCf6Sf4.png With the "Moogle" group closed

Maybe use a different icon for open folder if possible then, as it looks weird when the folder keeps the same state opened or closed.

2023-01-22 09:21 UTC, merged

2023-01-22 09:21 UTC, rootdarkarchon commented
Ty