Add DTR entry with number of visible pairs
Penumbra-Sync/client pull request #52
Opened 2023-06-08 11:13 UTC by Exter-N

I have no idea what I'm doing.

Jokes aside, this attempts to add the number of visible pairs (or a ❌ if disconnected) to the DTR/Server Info bar.

No settings were included as [Dalamud already provides them](https://github.com/goatcorp/Dalamud/discussions/745).

2023-06-10 14:58 UTC, rootdarkarchon requested changes
Please less overengineering

2023-06-10 14:58 UTC, rootdarkarchon commented on MareSynchronos/Services/Mediator/Messages.cs
> +public record PairHandlerInvisibleMessage(string? PlayerName, OnlineUserIdentDto OnlineUser, PairHandler? Player) : MessageBase;
The params are unused in `DtrEntry` and can be removed

2023-06-10 14:58 UTC, rootdarkarchon commented on MareSynchronos/UI/DtrEntry.cs
> +        ++_visiblePairs;
why not use `PairManager.GetVisibleUsers().Count()`?

2023-06-10 14:58 UTC, rootdarkarchon commented on MareSynchronos/UI/DtrEntry.cs
> +        _started = true;
Why is this an `IHostedService`? The Startup does nothing different than the `ctor`. I do not believe it needs to be an `IHostedService`.

If you would want to make this `IHostedService` I'd rather recommend spawning a Task here that periodically polls and updates the `DtrBar` with the count from `PairManager`, Connected status from `IpcManager` and you get rid of all the events.

Mind `DtrBar` might need to be updated from main game thread so you need to inject `DalamudUtil` to be able to `.RunOnFrameworkThread()`.

As visible user count is not time critical this operation can be run once per second and loop `while` a `CancellationTokenSource` has not been cancelled.
The `StopAsync` should then .Cancel the `CancellationTokenSource` to stop the `while` loop.

2023-06-14 01:19 UTC, Exter-N commented on MareSynchronos/Services/Mediator/Messages.cs
> +public record PairHandlerInvisibleMessage(string? PlayerName, OnlineUserIdentDto OnlineUser, PairHandler? Player) : MessageBase;
I removed the event entirely, switching to the polling approach you suggested.

2023-06-14 01:21 UTC, Exter-N commented on MareSynchronos/UI/DtrEntry.cs
> +        ++_visiblePairs;
I went with something conceptually equivalent in the polling approach, just with a separate method that does the counting without instantiating the list.

2023-06-14 01:24 UTC, Exter-N commented on MareSynchronos/UI/DtrEntry.cs
> +        _started = true;
Done, though I didn't bother with `.RunOnFrameworkThread()` as Dalamud buffers the change (https://github.com/goatcorp/Dalamud/blob/aa2cd47ef347b1b8ab84556177d0f67c368b5355/Dalamud/Game/Gui/Dtr/DtrBarEntry.cs#L38-L42) and only applies them in OnFrameworkUpdate (https://github.com/goatcorp/Dalamud/blob/aa2cd47ef347b1b8ab84556177d0f67c368b5355/Dalamud/Game/Gui/Dtr/DtrBar.cs#L168) as said on Discord.

As for why this is an `IHostedService`, there's a bit of cargo cult TBH: nothing depends on `DtrEntry`, so it wouldn't get instantiated at all if I didn't turn it into a hosted service, but then again I don't know this dependency injection / service container library very well.

2023-06-18 19:13 UTC, rootdarkarchon requested changes

2023-06-18 19:13 UTC, rootdarkarchon commented on MareSynchronos/UI/DtrEntry.cs
> +        Clear();
I think this should be in `StopAsync()` as `StopAsync()` is called on plugin shutdown.

2023-06-18 19:13 UTC, rootdarkarchon commented on MareSynchronos/UI/DtrEntry.cs
> +        _entry.Shown = true;
I would prefer if this would be more akin to `if(enable entry && !shown) { shown = true } else if(!enable entry && shown) { shown = false }`

2023-06-18 19:13 UTC, rootdarkarchon commented on MareSynchronos/UI/DtrEntry.cs
> +        CancellationToken token = _cancellationTokenSource.Token;
you do not need to pass the token here as `_cancellationTokenSource` is private and never changed outside the initialization. Can also simplify code by doing `private CancellationTokenSource? _cancellationTokenSource = new()`.
then in `RunAsync()` do `while(!_cancellationTokenSource.IsCancellationRequested)`

2023-06-18 21:01 UTC, merged